export function PreviewView({ chromeUrl, siteName, description }) {
  return (
    <div className="flex min-h-0 flex-1 items-center justify-center p-6.5">
      <div className="flex h-full w-full max-w-245 flex-col overflow-hidden rounded-lg border border-gray-200 bg-white shadow-[0_1px_3px_rgba(0,0,0,0.05)]">
        <div className="flex h-9.5 flex-none items-center gap-2 border-b border-gray-200 px-3.5">
          <div className="flex gap-1.5">
            <span className="h-2 w-2 rounded-full bg-gray-200" />
            <span className="h-2 w-2 rounded-full bg-gray-200" />
            <span className="h-2 w-2 rounded-full bg-gray-200" />
          </div>
          <div className="flex h-5.5 flex-1 items-center rounded-[5px] bg-gray-100 px-2.5 font-mono text-[11px] text-gray-500">
            {chromeUrl}
          </div>
        </div>

        <div className="flex flex-1 flex-col items-center justify-center gap-3 px-10 py-17.5 text-center">
          <h1 className="text-[clamp(22px,3vw,30px)] font-bold tracking-[-0.02em]">
            {siteName}
          </h1>
          <p className="mx-auto max-w-105 text-sm text-gray-500">
            {description || "Generated by StackVibe."}
          </p>
          <p className="mt-4 text-xs text-gray-400">
            Live rendering of the generated app isn&apos;t wired up yet —
            check the Code tab to see the actual generated files.
          </p>
        </div>
      </div>
    </div>
  );
}
